
INSTALLED_APPS = [
    # ...existing code...
    'django.contrib.messages',
    # ...existing code...
]

MIDDLEWARE = [
    # ...existing code...
    'django.contrib.messages.middleware.MessageMiddleware',
    # ...existing code...
]