# Generated by Django 5.1.3 on 2024-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrea',
            name='biography',
            field=models.TextField(),
        ),
    ]
